#ifndef _VP_ENUMS_
#define _VP_ENUMS_
namespace VP
{  
    enum CharButtonId{
        BUTTON_BABY_MARIO,
        BUTTON_BABY_LUIGI,
        BUTTON_TOAD,
        BUTTON_TOADETTE,
        BUTTON_BABY_PEACH,
        BUTTON_BABY_DAISY,
        BUTTON_KOOPA_TROOPA,
        BUTTON_DRY_BONES,
        BUTTON_MARIO,
        BUTTON_LUIGI,
        BUTTON_YOSHI,
        BUTTON_BIRDO,
        BUTTON_PEACH,
        BUTTON_DAISY,
        BUTTON_DIDDY_KONG,
        BUTTON_BOWSER_JR,
        BUTTON_WARIO,
        BUTTON_WALUIGI,
        BUTTON_KING_BOO,
        BUTTON_ROSALINA,
        BUTTON_DONKEY_KONG,
        BUTTON_FUNKY_KONG,
        BUTTON_BOWSER,
        BUTTON_DRY_BOWSER,
        BUTTON_MII_A,
        BUTTON_MII_B
    };

    enum Transmission{
        DEFAULT,
        OUTSIDE,
        INSIDE
    };

    enum WeightClass{
        LIGHTWEIGHT,
        MEDIUMWEIGHT,
        HEAVYWEIGHT,
        MIIS
    };

    enum Gamemode{
        RACESETTING_MODE_NORMAL = 0x0,
        RACESETTING_MODE_BSS = 0x1,
        RACESETTING_MODE_BBB = 0x2,
        RACESETTING_MODE_CHAOTIC = 0x3,
        RACESETTING_MODE_NONE = 0x4
    };

    enum KartRestriction{
        KART_DEFAULTSELECTION,
        KART_KARTONLY,
        KART_BIKEONLY
    };

    enum CharacterRestriction{
        CHAR_DEFAULTSELECTION,
        CHAR_LIGHTONLY,
        CHAR_MEDIUMONLY,
        CHAR_HEAVYONLY
    };

    enum ExtraPageId{
        PAGE_TRANSMISSION_SELECT = PAGE_BATTLE_TOTAL_LEADERBOARDS,
        PAGE_MULTI_TRANSMISSION_SELECT = PAGE_COMPETITION_LEADERBOARD
    };
    
    enum ExtraSettingType{
        SETTINGSTYPE_VP = 3
    };

    enum ExtraSettings{ // +6 for scrollers
        SETTINGVP_RADIO_KARTSELECT = 0,
        SETTINGVP_RADIO_CHARSELECT = 1,

        SETTINGVP_SCROLLER_MODE = 0 + 6,
    };

    enum BMGIds{
        SETTINGVP_BUTTONCHANGE = 0x2f04,
        SETTINGVP_BUTTONCHANGE_DESC = 0x2f14,
        SETTINGVP_PAGE_DESC = 0x2f24,

        RADIO_MUSIC_TITLE = 0x6000,
        RADIO_MUSIC_DISABLED = 0x6010,
        RADIO_MUSIC_ENABLED = 0x6011,
        RADIO_MUSIC_DISABLED_DESC = 0x6100,
        RADIO_MUSIC_ENABLED_DESC = 0x6101,

        RADIO_KARTSELECT_TITLE = 0x5003,
        RADIO_KARTSELECT_DEFAULT = 0x5040,
        RADIO_KARTSELECT_KARTONLY = 0x5041,
        RADIO_KARTSELECT_BIKEONLY = 0x5042,
        RADIO_KARTSELECT_DEFAULT_DESC = 0x5400,
        RADIO_KARTSELECT_KARTONLY_DESC = 0x5401,
        RADIO_KARTSELECT_BIKEONLY_DESC = 0x5402,

        RADIO_CHARSELECT_TITLE = 0x5004,
        RADIO_CHARSELECT_DEFAULT = 0x5050,
        RADIO_CHARSELECT_LIGHTONLY = 0x5051,
        RADIO_CHARSELECT_MEDIUMONLY = 0x5052,
        RADIO_CHARSELECT_HEAVYONLY  = 0x5053,
        RADIO_CHARSELECT_DEFAULT_DESC = 0x5500,
        RADIO_CHARSELECT_LIGHTONLY_DESC = 0x5501,
        RADIO_CHARSELECT_MEDIUMONLY_DESC = 0X5502,
        RADIO_CHARSELECT_HEAVYONLY_DESC = 0x5503,
        
        SCROLLER_MODE_TITLE = 0x6700,
        SCROLLER_MODE_NONE = 0x6710,
        SCROLLER_MODE_BSS = 0x6711,
        SCROLLER_MODE_BBB = 0x6712,
        SCROLLER_MODE_CHAOTIC = 0x6713,
        SCROLLER_MODE_NONE_DESC = 0x6800,
        SCROLLER_MODE_BSS_DESC = 0x6801,
        SCROLLER_MODE_BBB_DESC = 0x6802,
        SCROLLER_MODE_CHAOTIC_DESC = 0x6803,

        TRANSMISSION_OUTSIDE = 0x15000,
        TRANSMISSION_INSIDE = 0x15001,
        TRANSMISSION_OUTSIDE_BOTTOM = 0x15002,
        TRANSMISSION_INSIDE_BOTTOM = 0x15003,
        TRANSMISSION_HELP = 0x15004,
        TRANSMISSION_HELP_BOTTOM = 0x15005,
        TRANSMISSION_HELP_DESC = 0x15006,
        TRANSMISSION_TITLE = 0x15007
    };
} // namespace VP
#endif