#ifndef _VP_ENUMS_
#define _VP_ENUMS_
namespace VP
{  
    enum CharButtonId{
        BUTTON_BABY_MARIO,
        BUTTON_BABY_LUIGI,
        BUTTON_TOAD,
        BUTTON_TOADETTE,
        BUTTON_BABY_PEACH,
        BUTTON_BABY_DAISY,
        BUTTON_KOOPA_TROOPA,
        BUTTON_DRY_BONES,
        BUTTON_MARIO,
        BUTTON_LUIGI,
        BUTTON_YOSHI,
        BUTTON_BIRDO,
        BUTTON_PEACH,
        BUTTON_DAISY,
        BUTTON_DIDDY_KONG,
        BUTTON_BOWSER_JR,
        BUTTON_WARIO,
        BUTTON_WALUIGI,
        BUTTON_KING_BOO,
        BUTTON_ROSALINA,
        BUTTON_DONKEY_KONG,
        BUTTON_FUNKY_KONG,
        BUTTON_BOWSER,
        BUTTON_DRY_BOWSER,
        BUTTON_MII_A,
        BUTTON_MII_B
    };

    enum Transmission{
        TRANSMISSION_DEFAULT,
        TRANSMISSION_OUTSIDE,
        TRANSMISSION_INSIDE
    };

    enum WeightClass{
        LIGHTWEIGHT,
        MEDIUMWEIGHT,
        HEAVYWEIGHT,
        MIIS
    };

    enum Gamemode{
        GAMEMODE_NORMAL,
        GAMEMODE_BSS,
        GAMEMODE_BBB,
        GAMEMODE_CHAOTIC,
        GAMEMODE_NONE
    };

    enum KartRestriction{
        KART_DEFAULTSELECTION,
        KART_KARTONLY,
        KART_BIKEONLY
    };

    enum CharacterRestriction{
        CHAR_DEFAULTSELECTION,
        CHAR_LIGHTONLY,
        CHAR_MEDIUMONLY,
        CHAR_HEAVYONLY
    };

    enum ExtraPageId{
        PAGE_TRANSMISSION_SELECT = PAGE_BATTLE_TOTAL_LEADERBOARDS,
        PAGE_MULTI_TRANSMISSION_SELECT = PAGE_COMPETITION_LEADERBOARD
    };
    
    enum ExtraSettingType{
        SETTINGSTYPE_VP = 3
    };

    enum ExtraSettings{ // +6 for scrollers
        SETTINGVP_RADIO_KARTSELECT = 0,
        SETTINGVP_RADIO_CHARSELECT = 1,
        SETTINGVP_RADIO_FORCEDTRANS = 2,

        SETTINGVP_SCROLLER_MODE = 0 + 6,
    };

    enum DefaultBMGIds{
        BMG_VR_BOTTOM_100CC = 0x10e0,
        BMG_VR_BOTTOM_150CC = 0x10e1,
        BMG_VR_BOTTOM_MIRROR = 0x10e2,
        BMG_VR_BOTTOM_BALLOON = 0x10e3,
        BMG_VR_BOTTOM_COIN = 0x10e4,
    };

    enum CustomBMGIds{
        SETTINGVP_BUTTONCHANGE = 0x2f04,
        SETTINGVP_BUTTONCHANGE_DESC = 0x2f14,
        SETTINGVP_PAGE_DESC = 0x2f24,

        RADIO_KARTSELECT_TITLE = 0x6000,
        RADIO_KARTSELECT_DEFAULT = 0x6010,
        RADIO_KARTSELECT_KARTONLY = 0x6011,
        RADIO_KARTSELECT_BIKEONLY = 0x6012,
        RADIO_KARTSELECT_DEFAULT_DESC = 0x6100,
        RADIO_KARTSELECT_KARTONLY_DESC = 0x6101,
        RADIO_KARTSELECT_BIKEONLY_DESC = 0x6102,

        RADIO_CHARSELECT_TITLE = 0x6001,
        RADIO_CHARSELECT_DEFAULT = 0x6020,
        RADIO_CHARSELECT_LIGHTONLY = 0x6021,
        RADIO_CHARSELECT_MEDIUMONLY = 0x6022,
        RADIO_CHARSELECT_HEAVYONLY  = 0x6023,
        RADIO_CHARSELECT_DEFAULT_DESC = 0x6200,
        RADIO_CHARSELECT_LIGHTONLY_DESC = 0x6201,
        RADIO_CHARSELECT_MEDIUMONLY_DESC = 0X6202,
        RADIO_CHARSELECT_HEAVYONLY_DESC = 0x6203,

        RADIO_TRANSMISSION_TITLE = 0x6002,
        RADIO_TRANSMISSION_DEFAULT = 0x6030,
        RADIO_TRANSMISSION_OUTSIDE = 0x6031,
        RADIO_TRANSMISSION_INSIDE = 0x6032,
        RADIO_TRANSMISSION_DEFAULT_DESC = 0x6300,
        RADIO_TRANSMISSION_OUTSIDE_DESC = 0x6301,
        RADIO_TRANSMISSION_INSIDE_DESC = 0x6302,
        
        SCROLLER_MODE_TITLE = 0x6700,
        SCROLLER_MODE_NONE = 0x6710,
        SCROLLER_MODE_BSS = 0x6711,
        SCROLLER_MODE_BBB = 0x6712,
        SCROLLER_MODE_CHAOTIC = 0x6713,
        SCROLLER_MODE_NONE_DESC = 0x6800,
        SCROLLER_MODE_BSS_DESC = 0x6801,
        SCROLLER_MODE_BBB_DESC = 0x6802,
        SCROLLER_MODE_CHAOTIC_DESC = 0x6803,

        MENU_TRANSMISSION_OUTSIDE = 0x15000,
        MENU_TRANSMISSION_INSIDE = 0x15001,
        MENU_TRANSMISSION_OUTSIDE_BOTTOM = 0x15002,
        MENU_TRANSMISSION_INSIDE_BOTTOM = 0x15003,
        MENU_TRANSMISSION_HELP = 0x15004,
        MENU_TRANSMISSION_HELP_BOTTOM = 0x15005,
        MENU_TRANSMISSION_HELP_DESC = 0x15006,
        MENU_TRANSMISSION_TITLE = 0x15007,

        DISPLAY_GAMEMODE_NORMAL = 0x15008,
        DISPLAY_GAMEMODE_BSS = 0x15009,
        DISPLAY_GAMEMODE_BBB = 0x1500a,
        DISPLAY_GAMEMODE_CHAOTIC = 0x1500b,

        DISPLAY_FORCEDTRANS_OUTSIDE = 0x1500c,
        DISPLAY_FORCEDTRANS_INSIDE = 0x1500d,
    };
} // namespace VP
#endif